# Site settings
title: Meng Guo Wan - 技术博客
description: Meng Guo Wan 的个人技术博客，专注于 C++ 音视频开发、FFmpeg、WebRTC 及 Linux 底层技术。
favicon: /assets/img/avatar.svg
baseurl: /blog
url: https://prometheam.github.io
rss_url:

# Build settings

highlight: true
#highlighter: rouge

timezone: Asia/Shanghai

permalink: /:year/:month/:day/:title/

# _config.yml
markdown: kramdown
kramdown:
  input: GFM            # GitHub 风格 Markdown（支持表格、任务列表、删除线等）
  hard_wrap: false      # 禁用单换行转 <br>
  syntax_highlighter: rouge
  gfm_quirks: [paragraph_end]

plugins:
  - jekyll-feed

# 启用归档功能
collections:
  archives:
    output: true
    permalink: /archives/:year/:month/:day/:title/

# 默认设置
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post_layout"
      show_in_archives: true
      
